In [ ]:
#creating a list
import numpy as np
List = [1,2,3,4,5]
List*3



[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
#creating a array
array = np.array([1,2,3,4,5])
array*3


array([ 3,  6,  9, 12, 15])

In [ ]:
#2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


In [ ]:
#creating range of values in array
import numpy as np
np.arange(1,10,2)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#indexing and slicing for 1d array
import numpy as np
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[1:3])
print(arr[-1])


10
[20 30]
40


In [ ]:
#indexing and slicing for 2D array
import numpy as np
arr2=np.array([[10,20,30],[40,50,60]])
print(arr2[0,0])
print(arr2[0,2])
print(arr2[1,2])

10
30
60
